import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "./theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"antialiased bg-background"}>
        <ChakraProvider theme={theme}>
          <Header />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
