import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiTailwindcss,
  SiChakraui,
  SiBootstrap,
  SiMui,
  SiRedux,
  SiJest,
  SiNodedotjs,
  SiNestjs,
  SiPrisma,
  SiMysql,
  SiPostgresql,
  SiShadcnui,
} from "react-icons/si";

export const skillsList = [
  { icon: SiHtml5, text: "HTML" },
  { icon: SiCss3, text: "CSS" },
  { icon: SiJavascript, text: "JAVASCRIPT" },
  { icon: SiTypescript, text: "TYPESCRIPT" },
  { icon: SiReact, text: "REACT" },
  { icon: SiNextdotjs, text: "NEXT" },
  { icon: SiVuedotjs, text: "VUE" },
  { icon: SiTailwindcss, text: "TAILWIND" },
  { icon: SiChakraui, text: "CHAKRA UI" },
  { icon: SiBootstrap, text: "BOOTSTRAP" },
  { icon: SiMui, text: "MATERIAL UI" },
  { icon: SiShadcnui, text: "SHADCN UI" },
  { icon: SiRedux, text: "REDUX" },
  { icon: SiJest, text: "JEST" },
  { icon: SiNodedotjs, text: "NODE" },
  { icon: SiNestjs, text: "NEST" },
  { icon: SiPrisma, text: "PRISMA" },
  { icon: SiMysql, text: "MYSQL" },
  { icon: SiPostgresql, text: "POSTGRESQL" },
];
